# Generated by Django 4.1.5 on 2023-01-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='job',
            field=models.CharField(choices=[('CE', 'Computer Engineering'), ('EEE', 'Electrical-Electronics Engineering'), ('CiE', 'Civil Engineering'), ('ME', 'Mechanical Engineering')], default='CE', max_length=3),
        ),
    ]
